version: '3'
services:
  psql:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - psql:/var/lib/postgresql/data

volumes:
  psql: