// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IUserController is an autogenerated mock type for the IUserController type
type IUserController struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx
func (_m *IUserController) Delete(ctx *gin.Context) {
	_m.Called(ctx)
}

// Detail provides a mock function with given fields: ctx
func (_m *IUserController) Detail(ctx *gin.Context) {
	_m.Called(ctx)
}

// Register provides a mock function with given fields: ctx
func (_m *IUserController) Register(ctx *gin.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewIUserController interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUserController creates a new instance of IUserController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUserController(t mockConstructorTestingTNewIUserController) *IUserController {
	mock := &IUserController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
